version: "3.9"
services:
  alertmanager:
    restart: "unless-stopped"
    image: prom/alertmanager
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - --config.file
      - /etc/alertmanager/config.yml
      - --storage.path
      - /alertmanager
      - --log.level
      - ${LOG_LEVEL}
    ports:
      - 9093:9093/tcp
    depends_on:
      - prometheus

volumes:
  alertmanager-data:
