#Deprecated v1 testnet, will eventually be removed or changed
version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  ssv-node:
    restart: "unless-stopped"
    image: bloxstaking/ssv-node:${SSV_NODE_TAG:-latest}
    user: 12000:12000
    volumes:
      - ./blox-ssv-config.yaml:/config.yaml
      - ssv-data:/tmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HOST_IP:-0.0.0.0}:${SSV_P2P_PORT}:${SSV_P2P_PORT}/tcp
      - ${HOST_IP:-0.0.0.0}:${SSV_P2P_PORT_UDP}:${SSV_P2P_PORT_UDP}/udp
    <<: *logging
    environment:
      - CONFIG_PATH=/config.yaml
      - HOME=/tmp
    command: make BUILD_PATH=/go/bin/ssvnode start-node
  ssv-generate-keys:
    profiles: ["tools"]
    restart: "no"
    image: bloxstaking/ssv-node:${SSV_NODE_TAG:-latest}
    command: /go/bin/ssvnode generate-operator-keys
volumes:
  ssv-data:
