version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NIM_DOCKER_TAG}
      dockerfile: ${NIM_DOCKERFILE}
    image: nimbus:local
    user: user
    stop_grace_period: 1m
    volumes:
      - nimbus-consensus-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8008/tcp
    ports:
      - ${CC_P2P_PORT:-9000}:${CC_P2P_PORT:-9000}/tcp
      - ${CC_P2P_PORT:-9000}:${CC_P2P_PORT:-9000}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --status-bar=false
      - --tcp-port=${CC_P2P_PORT:-9000}
      - --udp-port=${CC_P2P_PORT:-9000}
      - --max-peers=${NIM_PEER_COUNT}
      - --network=${NETWORK}
      - --web3-url=${EC_NODE}
      - --web3-url=${EC_FALLBACK_NODE1}
      - --web3-url=${EC_FALLBACK_NODE2}
      - --log-level=${LOG_LEVEL}
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=5052
      - --enr-auto-update=true
      - --num-threads=0
      - --doppelganger-detection=false
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
      - --validator-monitor-totals
    labels:
      - traefik.enable=true
      - traefik.http.routers.cc.service=cc
      - traefik.http.routers.cc.entrypoints=websecure
      - traefik.http.routers.cc.rule=Host(`${CC_HOST}.${DOMAIN}`)
      - traefik.http.routers.cc.tls.certresolver=letsencrypt
      - traefik.http.services.cc.loadbalancer.server.port=5052
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  nimbus-consensus-data:
