version: "3.4"
services:
  execution:
    restart: "${RESTART}"
    build:
      context: ./openethereum
      dockerfile: ${OE_DOCKERFILE}
      args:
        - BUILD_TARGET=${OE_SRC_BUILD_TARGET}
        - DOCKER_TAG=${OE_DOCKER_TAG}
    image: openethereum:local
    user: openethereum
    stop_grace_period: 3m
    volumes:
      - oe-eth1-data:/var/lib/openethereum
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    entrypoint:
      - openethereum
      - --no-ipc
      - --no-secretstore
      - --base-path=/var/lib/openethereum
      - --jsonrpc-interface=all
      - --jsonrpc-apis=web3,eth,pubsub,net
      - --jsonrpc-hosts=all
      - --ws-interface=all
      - --ws-apis=web3,eth,pubsub,net
      - --ws-hosts=all
      - --ws-origins=all
      - --ws-port=${EL_WS_PORT:-8546}
      - --chain=${EL_NETWORK:-goerli}
      - --reseal-on-txs
      - none
      - --port
      - ${EL_P2P_PORT:-30303}
      - --jsonrpc-port
      - ${EL_RPC_PORT:-8545}
      - --logging
      - ${LOG_LEVEL}
      - --metrics
      - --metrics-port=6060
      - --metrics-interface=all
      - --snapshot-peers
      - "250"
      - --cache-size
      - "4096"
  eth:
    depends_on:
      - execution
volumes:
  oe-eth1-data:
