# Prometheus federation, or other reasons to have prometheus through traefik
version: "3.4"
services:
  prometheus:
    labels:
      - traefik.enable=true
      - traefik.http.routers.prom.entrypoints=web,websecure
      - traefik.http.routers.prom.rule=Host(`${PROM_HOST}.${DOMAIN}`)
      - traefik.http.routers.prom.tls.certresolver=letsencrypt
      - traefik.http.services.prom.loadbalancer.server.port=9090
