version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  validator:
    restart: "${RESTART}"
    build:
      context: ./teku
      args:
        - BUILD_TARGET=${TEKU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${TEKU_DOCKER_TAG}
      dockerfile: ${TEKU_DOCKERFILE}
    image: teku:local
    user: teku
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /opt/teku/bin/teku
      - validator-client
      - --beacon-node-api-endpoint=${CL_NODE:-http://consensus:5052}
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --network=auto
      - --validators-keystore-locking-enabled=true
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
      - --validators-graffiti=${GRAFFITI}
      - --validators-early-attestations-enabled=false
      - --validator-api-enabled=true
      - --validator-api-port=${KEY_API_PORT:-7500}
      - --validator-api-host-allowlist=*
      - --validator-api-cors-origins=*
      - --validator-api-keystore-file=/var/lib/teku/teku-keyapi.keystore
      - --validator-api-keystore-password-file=/var/lib/teku/teku-keyapi.password
      - --validators-proposer-default-fee-recipient=${REWARDS_TO}
  validator-import:
    restart: "no"
    image: teku:local
    user: root
    volumes:
      - teku-data:/var/lib/teku
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
    entrypoint: validator-import.sh
  validator-exit:
    restart: "no"
    image: teku:local
    user: teku
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /opt/teku/bin/teku
      - voluntary-exit
      - --beacon-node-api-endpoint=${CL_NODE:-http://consensus:5052}
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
  validator-list:
    restart: "no"
    image: teku:local
    user: teku
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        for file in /var/lib/teku/validator-keys/*; do
          echo -n "0x"
          cat $${file} | jq -r .pubkey
        done
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - validator
volumes:
  teku-data:
